In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
from sklearn.linear_model import LinearRegression
import statsmodels.formula.api as smf
from sklearn.model_selection import train_test_split

In [3]:
df=pd.DataFrame({'x':[7.8,6.0,5.6],'y':[3.5,4.8,7.6]})

In [4]:
df

x    y
0  7.8  3.5
1  6.0  4.8
2  5.6  7.6

In [5]:
df1=df[1:]

In [6]:
df1

x    y
1  6.0  4.8
2  5.6  7.6

In [8]:
m1=smf.ols('y~x',df1).fit()

In [9]:
m1.params

Intercept    46.8
x            -7.0
dtype: float64

In [13]:
#res=m1.predict(7.8)

In [14]:
df2=df[:2]

In [15]:
df2

x    y
0  7.8  3.5
1  6.0  4.8

In [16]:
m2=smf.ols('y~x',df2).fit()

In [17]:
m2.params

Intercept    9.133333
x           -0.722222
dtype: float64

In [18]:
m2.predict()

array([3.5, 4.8])

In [19]:
df=pd.DataFrame({'x':[7.8,6.0],'y':[3.5,4.8]})

In [20]:
x=df[['x']]
y=df[['y']]
xt=pd.DataFrame({'x':[5.6],'y':[7.6]})
xtest=xt[['x']]
ytest=xt[['y']]

In [21]:
xtest

x
0  5.6

In [22]:
m1=LinearRegression()
m1.fit(x,y)
m1_predict=m1.predict(xtest)

In [23]:
m1_predict

array([[5.08888889]])

In [24]:
df1=pd.DataFrame({'x':[6.0,5.6],'y':[4.8,7.6]})

In [25]:
x=df1[['x']]
y=df1[['y']]
xt1=pd.DataFrame({'x':[7.8],'y':[3.5]})
xtest1=xt1[['x']]
ytest1=xt1[['y']]

In [26]:
m2=LinearRegression()
m2.fit(x,y)
m2_predict=m1.predict(xtest1)

In [27]:
m2_predict

array([[3.5]])

In [28]:
df

x    y
0  7.8  3.5
1  6.0  4.8

In [29]:
x5=pd.DataFrame([7.8,6.0])
y5=pd.DataFrame([3.5,4.8])
xt=pd.DataFrame([5.6])
yt=pd.DataFrame([7.6])

In [30]:
m5=LinearRegression()
m5.fit(x5,y5)
m5_predict=m1.predict(xt)

In [31]:
m5_predict

array([[5.08888889]])

In [32]:
df9=pd.DataFrame({'x':[7.8,6.0,5.6],'y':[3.5,4.8,7.6]})

In [33]:
df9

x    y
0  7.8  3.5
1  6.0  4.8
2  5.6  7.6

In [34]:
x6=pd.DataFrame([5.6,6.0])
y6=pd.DataFrame([7.6,4.8])
xt3=pd.DataFrame([7.8])
yt3=pd.DataFrame([3.5])

In [35]:
m6=LinearRegression()
m6.fit(x6,y6)
m6_predict=m6.predict(xt3)

In [36]:
m6_predict

array([[-7.8]])

In [37]:
x7=pd.DataFrame([7.8,5.6])
y7=pd.DataFrame([3.5,7.6])
xt2=pd.DataFrame([6.0])
yt2=pd.DataFrame([4.8])

In [38]:
m7=LinearRegression()
m7.fit(x7,y7)
m7_predict=m7.predict(xt2)

In [39]:
m7_predict

array([[6.85454545]])